### PR TITLE
MAINT: Add contribution guide and automate formatting using Husky

### PR DESCRIPTION
**Pull request by richford**

### CODE REVIEW

**Comment by Emily-ejag** [comment]
Hi @richford , I can't access through Gmail it kinda flashes out, I tried Opera and Chrome:


https://github.com/yeatmanlab/roar-dashboard/assets/62304493/0cb09284-5bb4-43a9-8afa-7c060c65d774

**Comment by Emily-ejag** [comment]
image

**Review by Emily-ejag — CHANGES_REQUESTED** [review]
Can't access through gmail or clever

**Comment by richford** [comment]
@Emily-ejag, there's some issue with the GitHub action that creates the PR preview links. It no longer adds the preview link to the list of authorized domains for Google authentication. Clever auth has never worked for PR preview links. However, I don't think any of that should be a blocker for this PR as this PR doesn't actually change anything about the website. It only adds a `CONTRIBUTING.md` file and updates the pre-commit hook to check formatting.

**Comment by Emily-ejag** [comment]
> @Emily-ejag, there's some issue with the GitHub action that creates the PR preview links. It no longer adds the preview link to the list of authorized domains for Google authentication. Clever auth has never worked for PR preview links. However, I don't think any of that should be a blocker for this PR as this PR doesn't actually change anything about the website. It only adds a `CONTRIBUTING.md` file and updates the pre-commit hook to check formatting.

Hi @richford thank you for checking, I know it is not directly affecting the dashboard, just making sure :) Thank you for clarifying about GitHub action.

**Review by Emily-ejag — APPROVED** [review]

**Review by kellyel — APPROVED** [review]
Language looks great. Approving then adding a page to the docs!

**Pull request merged**
