### PR TITLE
Compress of Expand Tables in Dashboard

### PR DESCRIPTION
**Pull request by Emily-ejag**
Button to compress/expand the rows on a table for preference

### CODE REVIEW

**Review by richford — CHANGES_REQUESTED** [review]
Looking good! I noticed that the compress/expand button is missing from the list-users table (the one accessed by clicking on the "users" button in the last column of the list-orgs table.

I think it'd be nice if all of the tables had the same compress/expand button. Can you add it there. Then I think we're good to go.

**Comment by Emily-ejag** [comment]
The issue was that exporting was not allowed in the list-users table, so I moved the v-if out of the` span` and added the buttons

**Comment by richford** [comment]
Hi Emily, I'm still not seeing the expand/compress button in the list users table on the PR preview link.

**Comment by Emily-ejag** [comment]
The button is there. It was showing in my localhost. But after the rebase is in the PR link now

**Review by richford — APPROVED** [review]

**Pull request merged**
