### PR TITLE
FIX legal doc popping up

### PR DESCRIPTION
**Pull request by Emily-ejag**
## Proposed changes

Please link this PR with the Firekit PR: https://github.com/yeatmanlab/roar-firekit/pull/143

## Types of changes

What types of changes does this pull request introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (non-breaking change that does not add functionality but makes code cleaner or more efficient)
- [ ] Documentation Update
- [ ] Tests (new or updated tests)
- [ ] Style (changes to code styling)
- [ ] CI (continuous integration changes)
- [ ] Repository Maintenance
- [ ] Other (please describe below)

## Checklist

- [ ] I have read the [guidelines for contributing](https://github.com/yeatmanlab/roar-dashboard/blob/main/.github/CONTRIBUTING.md).
- [ ] The changes in this PR are as small as they can be. They represent one and only one fix or enhancement.
- [ ] Linting checks pass with my changes.
- [ ] Any existing unit tests pass with my changes.
- [ ] Any existing end-to-end tests pass with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] If this PR fixes an existing issue, I have added a unit or end-to-end test that will detect if this issue reoccurs.
- [ ] I have added JSDoc comments as appropriate.
- [ ] I have added the necessary documentation to the [roar-docs repository](https://github.com/yeatmanlab/roar-docs).
- [x] I have shared this PR on the roar-pr-reviews channel (if I have access)
- [ ] I have linked relevant issues (if any)

### CODE REVIEW

**Comment by ksmontville** [comment]
Getting this when selecting an administration which uses the ROAR Clinic Consent pdf:

image

Not sure if it's related to this specific PR.

**Comment by ksmontville** [comment]
It seems that the first time a new user logs in and accepts a consent form for the first time, it does not properly update the consent status on the client side. 

It will update properly on the back end, but on the front end the legal status doesn't update. So the user ends up accepting a second consent form, and then it properly updates. The result is two consent forms both on the front end and the back end.

I think the solution might be to make sure that the front end ref which stores the legal information is properly being updated whtin the logic, or it may involve re-fetching the legal data from Firestore after accepting the consent.

image

image

**Review by ksmontville — DISMISSED** [review]
See comments and images within thread.

**Comment by Emily-ejag** [comment]
> Getting this when selecting an administration which uses the ROAR Clinic Consent pdf:
> 
> image
> 
> Not sure if it's related to this specific PR.

Yes, the adobesign one will be different. It is listed but not used currently until de adobe sign PR gets merged

**Comment by Emily-ejag** [comment]
> It seems that the first time a new user logs in and accepts a consent form for the first time, it does not properly update the consent status on the client side.
> 
> It will update properly on the back end, but on the front end the legal status doesn't update. So the user ends up accepting a second consent form, and then the legal status properly updates on the client side. The result is two consent forms both on the front end and the back end.
> 
> Then we are no longer prompted for consent, so something is or is not happening on that first legal document acceptance,
> 
> I think the solution might be to make sure that the front end ref which stores the legal information is properly being updated whtin the logic, or it may involve re-fetching the legal data from Firestore after accepting the consent.

Interesting, so is it popping twice?

**Comment by ksmontville** [comment]
> > It seems that the first time a new user logs in and accepts a consent form for the first time, it does not properly update the consent status on the client side.
> > It will update properly on the back end, but on the front end the legal status doesn't update. So the user ends up accepting a second consent form, and then the legal status properly updates on the client side. The result is two consent forms both on the front end and the back end.
> > Then we are no longer prompted for consent, so something is or is not happening on that first legal document acceptance,
> > I think the solution might be to make sure that the front end ref which stores the legal information is properly being updated whtin the logic, or it may involve re-fetching the legal data from Firestore after accepting the consent.
> 
> Interesting, so is it popping twice?

Yes, the consent is popping up twice.

Log in -> accept consent form -> select a different administration -> accept consent again -> select different administration -> no consent form shows

So it is not properly saving the state of the user's legal information the first time the consent form is accepted. It takes two accepts in order for the client side to update the legal information properly.

**Comment by Emily-ejag** [comment]
> ent admin

Oh probably I need to checkout the updateConsent! probably it is not updating right away. Thanks for checking this @ksmontville !

**Pull request merged**
