### PR TITLE
Refreshing buttons css

### PR DESCRIPTION
**Pull request by Emily-ejag**
## Proposed changes

Delete the scss and css files for buttons which were overwriting Prime Flex / Prime Vue.
Make the current buttons as similar as possible using in-line Prime Flex.

## Types of changes

What types of changes does this pull request introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (non-breaking change that does not add functionality but makes code cleaner or more efficient)
- [ ] Documentation Update
- [ ] Tests (new or updated tests)
- [x] Style (changes to code styling)
- [ ] CI (continuous integration changes)
- [x] Repository Maintenance
- [ ] Other (please describe below)

## Checklist

- [x] I have read the [guidelines for contributing](https://github.com/yeatmanlab/roar-dashboard/blob/main/.github/CONTRIBUTING.md).
- [x] The changes in this PR are as small as they can be. They represent one and only one fix or enhancement.
- [x] Linting checks pass with my changes.
- [x] Any existing unit tests pass with my changes.
- [x] Any existing end-to-end tests pass with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] If this PR fixes an existing issue, I have added a unit or end-to-end test that will detect if this issue reoccurs.
- [ ] I have added JSDoc comments as appropriate.
- [ ] I have added the necessary documentation to the [roar-docs repository](https://github.com/yeatmanlab/roar-docs).
- [ ] I have shared this PR on the roar-pr-reviews channel (if I have access)
- [ ] I have linked relevant issues (if any)

### CODE REVIEW

**Review by lucasxsong — CHANGES_REQUESTED** [review]
Yay! The new buttons look good. I've attached a few comments below.

Screenshot 2024-06-11 at 10 12 25 AM
I think these buttons should have no background.

Screenshot 2024-06-11 at 10 14 46 AM

The score/progress report buttons were previously slightly grey on hover. Could we retain that behavior?

Screenshot 2024-06-11 at 10 16 11 AM
I think the logout button should be a text button (I've attached another screenshot of the button on roar.education for reference).
Screenshot 2024-06-11 at 10 16 41 AM

**Comment by Emily-ejag** [comment]
> Yay! The new buttons look good. I've attached a few comments below.
> 
> Screenshot 2024-06-11 at 10 12 25 AM I think these buttons should have no background. Screenshot 2024-06-11 at 10 14 46 AM
> The score/progress report buttons were previously slightly grey on hover. Could we retain that behavior?
> 
> Screenshot 2024-06-11 at 10 16 11 AM I think the logout button should be a text button (I've attached another screenshot of the button on roar.education for reference). Screenshot 2024-06-11 at 10 16 41 AM

Thank you! I solved the comments!

**Comment by Zio-4** [comment]
@Zio-4 Tagging myself to check the changes on the Levante instance.

**Review by lucasxsong — APPROVED** [review]

**Comment by Zio-4** [comment]
I noticed some unstyled elements that affect both projects and some that affect only LEVANTE.

**Shared:**
Delete administration prompt
Admin-delete-prompt

Administration date picker (start and end date)
Admin-date-picker
Admin-end-date-picker


Clearing Administrations search
Admin-clear-search

**LEVANTE**
Register users page
Admin-users-uploader-levante-only

Child survey (start page and survey page)
child-survey-page-1
child-survey-page-2

For the LEVANTE elements could you use the same button styles as ROAR is using?

**Review by Zio-4 — CHANGES_REQUESTED** [review]
Comments above

**Review by Zio-4 — APPROVED** [review]

**Pull request merged**
