### PR TITLE
Use exported CSS in all of the task components

### PR DESCRIPTION
**Pull request by richford**
This is a companion PR to the following ROAR app PRs:

- https://github.com/yeatmanlab/roar-swr/pull/183
- https://github.com/yeatmanlab/roar-pa/pull/78
- https://github.com/yeatmanlab/roar-sre/pull/79
- https://github.com/yeatmanlab/roar-letter/pull/56
- https://github.com/yeatmanlab/roar-multichoice/pull/58
- https://github.com/yeatmanlab/roar-vocab/pull/26
- https://github.com/yeatmanlab/ROAM-Fluency/pull/10

And it's currently WIP because it won't work until we merge those PRs and update the package.json.

### CODE REVIEW

**Comment by Emily-ejag** [comment]
Looks good to me

**Review by Emily-ejag — APPROVED** [review]

**Comment by richford** [comment]
@kellyel, @ksmontville, and @Emily-ejag, I believe I've resolved the issues and this is ready for review. Could I ask you to test participant view:
- Load a task, confirm that styling is good
- Refresh that task, confirm that styling is still good
- Use the back button to go back to the home view
- Select a different task, confirm that styling is good
- Refresh, confirm it's good
- Complete that task, which should automatically direct you back to the home view.
- Select another task, confirm that the styling is good.

You can use the `labTestUserXX` accounts. Let's assign different tasks to each of you for testing purposes:
- [ ] (@kellyel) task 1: SWR, task 2: Letter, task 3: SRE
- [ ] (@ksmontville) task 1: PA, task 2: Morphology, task 3: Letter
- [ ] (@Emily-ejag) task 1: SRE, task 2: Palabra, task 3: PA

**Comment by Emily-ejag** [comment]
Used labTestUser18, the preview URL gave many issues, but it works perfectly on localhost
with the link: 
image
image
image
image

Also, there is no link to the style sheet in the URL.

For the localhost there is just 1: 
image

It worked great in all the steps

**Comment by Emily-ejag** [comment]
It is working now for the tasks assigned to me

**Review by Emily-ejag — APPROVED** [review]

**Comment by richford** [comment]
Task linked: [CU-8686pezrg Resolve style file packaging issue](https://app.clickup.com/t/8686pezrg)

**Review by ksmontville — APPROVED** [review]

**Pull request merged**
