### PR TITLE
WIP: Parent SignUp with OrgCode

### PR DESCRIPTION
**Pull request by Emily-ejag**
adding orgCode per child

### CODE REVIEW

**Comment by richford** [comment]
@Emily-ejag, I think this PR is deprecated in favor of #638. Is that right? If so, I'll close this PR.

**Comment by Emily-ejag** [comment]
> @Emily-ejag, I think this PR is deprecated in favor of #638. Is that right? If so, I'll close this PR.

Yes I think you are right

**Comment by Emily-ejag** [comment]
Not longer need, the PR  #638 contemplates this

**Comment by Emily-ejag** [comment]
Not longer needed

**Pull request closed without merging**
