### PR TITLE
Enh/external tasks

### PR DESCRIPTION
**Pull request by Zio-4**

### CODE REVIEW

**Comment by Zio-4** [comment]
This PR also requires https://github.com/yeatmanlab/roar-firekit/pull/71

**Comment by richford** [comment]
I merged your firekit PR and released a new minor version of firekit: 3.13.0. @Zio-4, can you update this PR with the new version so that the preview link will work?

**Comment by richford** [comment]
Task linked: [CU-8685tjk6g Launch external tasks](https://app.clickup.com/t/8685tjk6g)

**Comment by Zio-4** [comment]
@richford This PR should now be ready to merge

**Review by richford — APPROVED** [review]

**Pull request merged**
